<?php


// Translation of file /modules/mail_form/views/form.inc

$_COS_LANG_MODULE['Fill out the contact form'] = 'Din formular er afsendt';
$_COS_LANG_MODULE['Title'] = 'Titel';
$_COS_LANG_MODULE['Your email'] = 'Din email';
$_COS_LANG_MODULE['Enter your message'] = 'Indhold';
$_COS_LANG_MODULE['Submit'] = 'Afsend';

// Translation of file /modules/mail_form/model.mail_form.inc

$_COS_LANG_MODULE['Not a correct email'] = 'Ikke en korrekt email';
$_COS_LANG_MODULE['Enter title'] = 'Indtast titel';
$_COS_LANG_MODULE['Enter content'] = 'Indtast indhold';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Ikke en korrekt udregning af captcha';

// Translation of file /modules/mail_form/index.php
