<?php

// Translation of file /home/dennis/www/mandlen/lib/../modules/mail_form/views/form.inc

$_COS_LANG_MODULE['mail_form'] = 'Udfyld kontakt formularen';
$_COS_LANG_MODULE['mail_form_title'] = 'Titel';
$_COS_LANG_MODULE['mail_form_email'] = 'Din email';
$_COS_LANG_MODULE['mail_form_content'] = 'Indhold';
$_COS_LANG_MODULE['mail_form_submit'] = 'Afsend';

// Translation of file /home/dennis/www/mandlen/lib/../modules/mail_form/model.mail_form.inc

$_COS_LANG_MODULE['mail_form_error_email'] = 'Ikke en korrekt email';
$_COS_LANG_MODULE['mail_form_error_title'] = 'Indtast titel';
$_COS_LANG_MODULE['mail_form_error_content'] = 'Indtast indhold';
$_COS_LANG_MODULE['mail_form_error_captcha'] = 'Ikke en korrekt udregning af captcha';

// Translation of file /home/dennis/www/mandlen/lib/../modules/mail_form/index.php

$_COS_LANG_MODULE['mail_form_sent'] = 'Din formular er afsendt';