<?php

$_COS_LANG_MODULE['Fill out the contact form'] = 'Skjemaet har blitt sendt';
$_COS_LANG_MODULE['Not a correct email'] = 'Ikke riktig e';
$_COS_LANG_MODULE['Enter title'] = 'Skriv inn tittel';
$_COS_LANG_MODULE['Enter content'] = 'Tast innhold';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Ikke en korrekt beregning av captcha';
$_COS_LANG_MODULE['Title'] = 'Tittel';
$_COS_LANG_MODULE['Your email'] = 'Din e-post';
$_COS_LANG_MODULE['Enter your message'] = 'Innhold';
$_COS_LANG_MODULE['Submit'] = 'Send inn';
