<?php

$_COS_LANG_MODULE['mail_form'] = 'Fill out the contact form';
$_COS_LANG_MODULE['mail_form_title'] = 'Title';
$_COS_LANG_MODULE['mail_form_email'] = 'Your email';
$_COS_LANG_MODULE['mail_form_content'] = 'Contents';
$_COS_LANG_MODULE['mail_form_submit'] = 'Submit';
$_COS_LANG_MODULE['mail_form_error_email'] = 'Not a correct email';
$_COS_LANG_MODULE['mail_form_error_title'] = 'Enter title';
$_COS_LANG_MODULE['mail_form_error_content'] = 'Enter content';
$_COS_LANG_MODULE['mail_form_error_captcha'] = 'Not a correct calculation of captcha';
$_COS_LANG_MODULE['mail_form_sent'] = 'Your form has been sent';
