<?php

$_COS_LANG_MODULE['Fill out the contact form'] = 'Lomake on lähetetty';
$_COS_LANG_MODULE['Not a correct email'] = 'Ei oikea email';
$_COS_LANG_MODULE['Enter title'] = 'Kirjoita otsikko';
$_COS_LANG_MODULE['Enter content'] = 'Anna sisällön';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Ei laskea oikein captcha';
$_COS_LANG_MODULE['Title'] = 'Otsikko';
$_COS_LANG_MODULE['Your email'] = 'Sähköpostiosoitteesi';
$_COS_LANG_MODULE['Enter your message'] = 'Sisältö';
$_COS_LANG_MODULE['Submit'] = 'Esittää';
