<?php

// Translation of file /home/dennis/www/sweetpoints/modules/mail_form/index.php

$_COS_LANG_MODULE['mail_form_sent'] = 'mail_form_sent';
// Translation of file /home/dennis/www/sweetpoints/modules/mail_form/model.mail_form.inc

$_COS_LANG_MODULE['mail_form_error_email'] = 'mail_form_error_email';
$_COS_LANG_MODULE['mail_form_error_title'] = 'mail_form_error_title';
$_COS_LANG_MODULE['mail_form_error_content'] = 'mail_form_error_content';
$_COS_LANG_MODULE['mail_form_error_captcha'] = 'mail_form_error_captcha';
// Translation of file /home/dennis/www/sweetpoints/modules/mail_form/views/form.inc

$_COS_LANG_MODULE['mail_form'] = 'mail_form';
$_COS_LANG_MODULE['mail_form_title'] = 'mail_form_title';
$_COS_LANG_MODULE['mail_form_email'] = 'mail_form_email';
$_COS_LANG_MODULE['mail_form_content'] = 'mail_form_content';
$_COS_LANG_MODULE['mail_form_submit'] = 'mail_form_submit';
