<?php

$_COS_LANG_MODULE['Fill out the contact form'] = 'Your form has been sent';
$_COS_LANG_MODULE['Title'] = 'Title';
$_COS_LANG_MODULE['Your email'] = 'Your email';
$_COS_LANG_MODULE['Enter your message'] = 'Enter your message';
$_COS_LANG_MODULE['Submit'] = 'Submit';
$_COS_LANG_MODULE['Not a correct email'] = 'Not a correct email';
$_COS_LANG_MODULE['Enter title'] = 'Enter title';
$_COS_LANG_MODULE['Enter content'] = 'Enter content';
$_COS_LANG_MODULE['Not a correct calculation of captcha'] = 'Not a correct calculation of captcha';
